name: Go

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']

jobs:

  test:
    runs-on: ${{ matrix.os }}
    env:
      HOST: localhost 
      PORT: 5432
      USER: root 
      PASSWWORD: root 
      DBNAME: root      
    strategy:
      matrix:
        go_version: ['1.19', '1.17', '1.18']
        os: ['ubuntu-latest']
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go_version }}

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Verify Docker Compose installation
        run: docker-compose --version
    
      - name: Verify Go installation
        run: |
          go version
          which go
          echo $PATH

      - name: Build-DB
        run: docker-compose build
      
      - name: Create-DB
        run: docker-compose up -d

      - name: Test
        run: go test -v ./...

  build:
    needs: test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go_version: ['1.19', '1.17', '1.18']
        os: ['ubuntu-latest']
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go_version }}

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Verify Docker Compose installation
        run: docker-compose --version

      - name: Build
        run: go build -v main.go
